# Generated by Django 3.0.4 on 2020-03-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_heading',
            new_name='heading',
        ),
    ]
